version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.12
    ports:
      - "1883:1883"
    volumes:
      - "${MOSQUITTO_CONF-./docker/mosquitto/mosquitto.conf}:/mosquitto/config/mosquitto.conf:ro"
      - "${MOSQUITTO_INCLUDE_DIR-./docker/mosquitto/conf.d}:/mosquitto/config/conf.d:ro"
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgres/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB:?}"
      - "POSTGRES_USER=${POSTGRES_USER:?}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}"
  integrator:
    image: maven:3.8.3-jdk-11
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "./integrator:/integrator"
      - "./.maven:/root/.m2"
    environment:
      - "INTEGRATOR_MQTT_URL=${INTEGRATOR_MQTT_URL:?}"
      - "INTEGRATOR_MQTT_USER=${INTEGRATOR_MQTT_USER}"
      - "INTEGRATOR_MQTT_PASS=${INTEGRATOR_MQTT_PASS}"
      - "DATABASE_URL=${POSTGRES_JDBC_URL:?}"
      - "DATABASE_NAME=${POSTGRES_DB:?}"
      - "DATABASE_USER=${POSTGRES_USER:?}"
      - "DATABASE_PASS=${POSTGRES_PASSWORD:?}"
    working_dir: "/integrator"
    command: "${INTEGRATOR_CONTAINER_START_COMMAND:-mvn compile quarkus:dev}"
